adds length-check to validation.
ilios/common pull request #1919
Opened 2021-02-03 00:10 UTC by stopfstedt

fixes #1918

2021-02-03 21:22 UTC, dartajax requested changes
If a 245 char URL is entered, it needs to wrap ...

![image](https://user-images.githubusercontent.com/7493331/106811206-da296800-6622-11eb-9658-ce35679f023b.png)

2021-02-03 21:25 UTC, stopfstedt commented
> If a 245 char URL is entered, it needs to wrap ...

different issue, please file separate ticket.

2021-02-03 21:30 UTC, dartajax approved these changes
if the main issue being fixed here is the 256 char max on URL, I approve

2021-02-03 21:37 UTC, merged

2021-02-03 21:52 UTC, stopfstedt commented
> if the main issue being fixed here is the 256 char max on URL, I approve

new issue: https://github.com/ilios/common/issues/1923

2021-02-04 17:03 UTC, jrjohnson commented on tests/integration/components/new-learningmaterial-test.js
> +    await component.url.set('https://validurl.edu/but-way-too-long/' + '0123456789'.repeat(25));
💚