Add breadcrumbs to course visualizations
ilios/common pull request #2295
Opened 2021-08-12 23:46 UTC by stopfstedt

fixes https://github.com/ilios/common/issues/2226

2021-08-16 23:29 UTC, dartajax requested changes
any chance we can have `Other Visualizations` become `Visualizations` instead?

![image](https://user-images.githubusercontent.com/7493331/129641498-6f4bd594-2211-4db6-9ad9-1de42fa1eb4e.png)

It's in the same context as `Learner Groups` now which does not say `Other Learner Groups` - dig?

2021-08-16 23:42 UTC, stopfstedt commented
> any chance we can have `Other Visualizations` become `Visualizations` instead?
you got it :+1:

2021-08-16 23:49 UTC, dartajax approved these changes

2021-08-17 17:33 UTC, jrjohnson approved these changes

2021-08-17 18:36 UTC, merged