octanifies term model.
ilios/common pull request #2475
Opened 2021-11-19 19:47 UTC by stopfstedt

2021-11-23 23:18 UTC, jrjohnson requested changes

2021-11-23 23:18 UTC, jrjohnson commented on addon/components/dashboard/selected-vocabulary.js
> +    this.args.vocabulary.getTopLevelTerms.bind(this.args.vocabulary),
Now it gets really interesting 😁

2021-11-23 23:18 UTC, jrjohnson commented on addon/components/dashboard/selected-vocabulary.js
> +    console.log(this._topLevelTerms);
```suggestion
```

2021-11-23 23:18 UTC, jrjohnson commented on addon/models/term.js
> +  get isTopLevel() {
This feels too useful to me to get rid of, but I'll accept it.

2021-11-23 23:59 UTC, stopfstedt commented on addon/components/detail-terms-list-item.hbs
> +  {{#unless (await @term.parent)}}
replaced as suggested. :heavy_check_mark:

2021-11-23 23:59 UTC, stopfstedt commented on addon/components/detail-terms-list-item.hbs
> +    {{#each (await this.allParentTitles) as |title|}}
:heavy_check_mark:

2021-11-24 00:07 UTC, jrjohnson approved these changes

2021-11-24 01:39 UTC, merged