Update Ember CLI to 4.2
ilios/common pull request #2814
Opened 2022-04-19 21:55 UTC by jrjohnson

With blueprint updates to get the latest ember version as well.

2022-04-19 22:47 UTC, jrjohnson commented
Tests that are pending have been replaced and are no longer valid, I'll pull them out once this is merged.

2022-04-26 17:01 UTC, stopfstedt requested changes

2022-04-26 17:18 UTC, jrjohnson commented on tests/dummy/config/environment.js
> +    locationType: 'history',
Auto is deprecated https://deprecations.emberjs.com/v4.x/#toc_deprecate-auto-location and history is the new ember-cli default.

2022-04-26 17:19 UTC, stopfstedt approved these changes
LGTM

2022-04-26 19:47 UTC, dartajax approved these changes
I click tested a bunch - looks fine. I'm assigned - gonna merge.

2022-04-26 19:47 UTC, merged