Corrects Course Instructor visualizations
ilios/common pull request #2955
Opened 2022-07-20 20:23 UTC by stopfstedt

fixes #2952 

this _only_ fixes the instructor visualizations, other course visualizations will need to be reviewed and possible fixed as a follow-up.

2022-07-20 22:13 UTC, saschaben commented
@stopfstedt the instructor time/percent donute seems on target, but the "terms" bar graphs appear to be counting the total course time associated with each, rather than the total instructor time associated with each. can you verify which it is? I *think* it should be total instructional time for each term for the selected instructor...

2022-07-20 23:02 UTC, stopfstedt commented
> @stopfstedt the instructor time/percent donute seems on target, but the "terms" bar graphs appear to be counting the total course time associated with each, rather than the total instructor time associated with each. can you verify which it is? I _think_ it should be total instructional time for each term for the selected instructor...


I think I  can answer that only partially, let  me try:
- the _total instructional time_ the given instructor teaches (in that course) for the given topic is correct.
- i am less sure about the percentages, and therefore the length of the bars in the terms chart. 

![image](https://user-images.githubusercontent.com/1410427/180096387-c3974240-5fad-4421-aec4-977481583cc3.png)

if you add all the instructional time that each topic is taught by this instructor up, and then put this into relation to each individual term, then this is the correct output.

For example: Cultural Humility is taught for 255 mins. If you add up all the minutes for all terms, you get a sum total of 1110 mins.
255 is 23% of 1110, so that checks out. However, total instructional time is 405mins for this instructor. 
we arrive at the inflated total of 1110 mins, because sessions have been tagged with multiple terms, which is not taken into consideration.
So perhaps a different formula should be applied here? and/or a different chart could be used? I have no idea.

2022-07-20 23:37 UTC, saschaben commented
I don't have an answer, but I think we can arrive at one. let's discuss.

2022-07-20 23:51 UTC, stopfstedt commented
> I don't have an answer, but I think we can arrive at one. let's discuss.
agreed. here's a quick and dirty adjustment - taking the percentage against the total instructional time instead of the inflated aggregate. 

![image](https://user-images.githubusercontent.com/1410427/180101490-6ee873be-026f-44d9-bb77-d541a672b6d3.png)

makes a lot more sense to me - 255 is 63% of 405.

2022-07-21 00:00 UTC, stopfstedt commented
work in progress: 

playing around with the labeling of the terms bars

![image](https://user-images.githubusercontent.com/1410427/180102337-a8439443-0443-4965-95a7-f6b649ee2020.png)


maybe this providing the context we need?

2022-07-21 15:12 UTC, stopfstedt commented
@saschaben - i pushed the code change that calculates percentage against the total sum of instructional ("offerings") time for each term, rather than the total aggregate of instructional time of all terms. 
even without a labeling change, the charted data makes a lot more sense to me now. 
please have another look.

2022-07-21 21:30 UTC, stopfstedt commented
@saschaben i changed the labeling to show minutes instead of percentages.

![image](https://user-images.githubusercontent.com/1410427/180318476-4ea5e8a0-0448-4d79-92f4-993d3c733d28.png)

does this pass muster?

2022-07-21 23:04 UTC, saschaben commented
@stopfstedt this DOES pass muster -- I really like the updates & the simplification of the labeling on the barchart. It makes a ton more intuitive sense now. Also the numbers are correct, which helps!

2022-07-26 20:39 UTC, jrjohnson requested changes

2022-07-26 21:03 UTC, stopfstedt commented on addon/components/course-visualize-instructor.js
> +  @use _sessions = new ResolveAsyncValue(() => [this.args.course.sessions]);
:heavy_check_mark:

2022-07-26 21:03 UTC, stopfstedt commented on addon/components/visualizer-course-instructor-session-type.js
> +  @use _sessions = new ResolveAsyncValue(() => [this.args.course.sessions]);
:heavy_check_mark:

2022-07-26 21:06 UTC, stopfstedt commented on addon-test-support/ilios-common/page-objects/components/visualizer-course-instructor-term.js
> +  isIcon: notHasClass('no-icon'),
agreed - it's awkward, but that's how it is currently. out of scope for this/should be improved as a follow-up item. 

https://github.com/ilios/common/pull/2955/files#diff-ba7bde41d71daf7d0b3489a0a0c85c689f245f1f9a5eff1821813943e8508520R2

2022-07-26 22:17 UTC, jrjohnson approved these changes
📈 📊 🎉

2022-07-26 22:58 UTC, merged