learning material manager layout fixes
ilios/common pull request #3002
Opened 2022-08-10 15:23 UTC by stopfstedt

fixes #3001

2022-08-10 17:22 UTC, dartajax requested changes
the description field needs some treatment too ...

<img width="1395" alt="Screen Shot 2022-08-10 at 10 21 37 AM" src="https://user-images.githubusercontent.com/7493331/183976726-af514123-d3e4-4cdf-8367-491ec42efbd7.png">

<img width="1105" alt="Screen Shot 2022-08-10 at 10 21 49 AM" src="https://user-images.githubusercontent.com/7493331/183976763-3c205399-58bf-4056-b464-891a7b368950.png">

2022-08-10 18:07 UTC, stopfstedt commented
> the description field needs some treatment too ...
> 
> <img alt="Screen Shot 2022-08-10 at 10 21 37 AM" width="1395" src="https://user-images.githubusercontent.com/7493331/183976726-af514123-d3e4-4cdf-8367-491ec42efbd7.png">
> 
> <img alt="Screen Shot 2022-08-10 at 10 21 49 AM" width="1105" src="https://user-images.githubusercontent.com/7493331/183976763-3c205399-58bf-4056-b464-891a7b368950.png">

nope, not going to break text in a text area. besides, this is not a realistic scenario.

2022-08-10 20:58 UTC, dartajax approved these changes

2022-08-11 06:34 UTC, jrjohnson approved these changes

2022-08-12 21:21 UTC, merged