rm back-link from event details page.
ilios/common pull request #3457
Opened 2023-07-14 23:04 UTC by stopfstedt

this came up as unnecessary and potentially confusing during a a11y audit. begone!

fixes https://github.com/ilios/ilios/issues/4774

2023-07-14 23:36 UTC, stopfstedt commented
i'm slapping a `do not merge` label on this since the companion PR https://github.com/ilios/lti-dashboard/pull/1373 is currenly failing.

2023-07-17 16:55 UTC, jrjohnson approved these changes

2023-07-17 17:34 UTC, dartajax commented
`DO NOT MERGE` label attached to this ticket - will merge once removed

2023-07-24 18:56 UTC, jrjohnson requested changes

2023-07-24 18:56 UTC, jrjohnson commented on addon/controllers/events.js
> +    const appConfig = getOwner(this).resolveRegistration('config:environment');
I *think* the way to do this has changed to [getConfig](https://github.com/embroider-build/embroider/tree/main/packages/macros#getownconfig-getconfig-and-getglobalconfig), but I haven't messed with it a lot. I'm ok with this solution, it works for sure, but we're already importing and using these macros other places so it's worth investigating.

2023-07-24 22:37 UTC, jrjohnson approved these changes

2023-08-21 21:41 UTC, stopfstedt commented
i'm starting over on this.

2023-08-21 21:41 UTC, closed without merging